[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "write", path = "./deploy/"}]

[lint]
# Several lints fail on acronyms like "ERC" instead of "Erc", so we exclude those
exclude_lints = [
    "pascal-case-struct",
    "mixed-case-function",
    "mixed-case-variable",
    "asm-keccak256",
    "unwrapped-modifier-logic"
]
ignore = [
    "src/interfaces/external/**/*.sol",
    "test/**/*.sol"
]
